COPYRIGHT_SYMBOL		EQU #7F

ROM_PAGE_SIZE           EQU #4000

ROM_PAGE_BANK0		    EQU 0
ROM_PAGE_TRDOS		    EQU 1
ROM_PAGE_128k   	    EQU 2
ROM_PAGE_48k    	    EQU 3

ROM_PAGE_BANK0_ADDR     EQU ROM_PAGE_SIZE * ROM_PAGE_BANK0
ROM_PAGE_TRDOS_ADDR     EQU ROM_PAGE_SIZE * ROM_PAGE_TRDOS
ROM_PAGE_128k_ADDR      EQU ROM_PAGE_SIZE * ROM_PAGE_128k
ROM_PAGE_48k_ADDR       EQU ROM_PAGE_SIZE * ROM_PAGE_48k
